apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-headless
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
        - name: fix-keyfile-permissions
          image: busybox
          command: ["sh", "-c", "chmod 600 /etc/secrets/mongodb-keyfile"]
          securityContext:
            privileged: true  # Allow initContainer to run with elevated privileges
          volumeMounts:
            - name: keyfile-secret
              mountPath: /etc/secrets
              readOnly: true  # Ensure this volume is mounted as read-only
      containers:
        - name: mongo
          image: {{ .Values.mongoImage }}
          args:
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"
            - "--auth"
            - "--keyFile"
            - "/etc/secrets/mongodb-keyfile"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-password
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: keyfile-secret
              mountPath: /etc/secrets
              readOnly: true  # Ensure this volume is mounted as read-only
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "chmod 600 /etc/secrets/mongodb-keyfile"
      volumes:
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
        - name: keyfile-secret
          secret:
            secretName: mongo-keyfile
            defaultMode: 0600  # Ensure the secret has proper permissions
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
