apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: mongodb1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-headless
  template:
    metadata:
      labels:
        app: mongo
    spec:
      initContainers:
        - name: fix-keyfile-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /etc/secrets/mongodb-keyfile /mnt/mongodb-keyfile
              chmod 600 /mnt/mongodb-keyfile
          volumeMounts:
            - name: keyfile-secret
              mountPath: /etc/secrets
              readOnly: true
            - name: temp-keyfile
              mountPath: /mnt

      containers:
        - name: mongo
          image: mongo:7.0.5
          args:
            - "--replSet"
            - "rs0"
            - "--bind_ip_all"
            - "--auth"
            - "--keyFile"
            - "/etc/secrets/mongodb-keyfile"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-password
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
            - name: temp-keyfile
              mountPath: /etc/secrets
              readOnly: true
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
        - name: keyfile-secret
          secret:
            secretName: mongo-keyfile
            defaultMode: 0400  # Minimum required permissions
        - name: temp-keyfile
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp2
        resources:
          requests:
            storage: 10Gi
