elasticsearch:
  replicaCount: 1
  image: "docker.elastic.co/elasticsearch/elasticsearch:8.5.1"
  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"
  storage:
    size: 10Gi
    accessMode: ReadWriteOnce
  service:
    type: ClusterIP
    port: 9200

kibana:
  replicaCount: 1
  image: "docker.elastic.co/kibana/kibana:8.5.1"
  service:
    type: ClusterIP
    port: 5601
  ingress:
    enabled: true
    host: kibana.example.com
