apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  vault-config.hcl: |
    storage "postgresql" {
      connection_url = "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.servicePort }}/{{ .Values.postgres.database }}?sslmode=disable"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
