apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image }}"
          ports:
            - containerPort: 9200
          env:
            {{- range .Values.elasticsearch.extraEnvs }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
            requests:
              memory: "{{ .Values.elasticsearch.resources.requests.memory }}"
              cpu: "{{ .Values.elasticsearch.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.elasticsearch.resources.limits.memory }}"
              cpu: "{{ .Values.elasticsearch.resources.limits.cpu }}"
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
