apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
spec:
  accessModes:
    - {{ .Values.elasticsearch.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.elasticsearch.storage.size }}
  storageClassName: {{ .Values.elasticsearch.storage.storageClassName }}
